"""Add translation fields to transcription history

Revision ID: 131075efe4f9
Revises: a305309c0544
Create Date: 2026-10-02 11:15:06.547073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '131075efe4f9'
down_revision = 'a305309c0544'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcription_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('translated_transcript', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('translation_language', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcription_history', schema=None) as batch_op:
        batch_op.drop_column('translation_language')
        batch_op.drop_column('translated_transcript')

    # ### end Alembic commands ###
