"""Add transcription history

Revision ID: a305309c0544
Revises: 60599f56365b
Create Date: 2026-09-30 13:10:55.282346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a305309c0544'
down_revision = '60599f56365b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transcription_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('structured_report', sa.Text(), nullable=True),
    sa.Column('structured_report_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transcription_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transcription_history_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transcription_history_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transcription_history_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcription_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transcription_history_user_id'))
        batch_op.drop_index(batch_op.f('ix_transcription_history_expires_at'))
        batch_op.drop_index(batch_op.f('ix_transcription_history_created_at'))

    op.drop_table('transcription_history')
    # ### end Alembic commands ###
